    Organizations:
    
        - &OrdererOrg
            Name: OrdererOrg
            ID: OrdererMSP
            MSPDir: crypto-config/ordererOrganizations/test.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('OrdererMSP.member')"
                Writers:
                    Type: Signature
                    Rule: "OR('OrdererMSP.member')"
                Admins:
                    Type: Signature
                    Rule: "OR('OrdererMSP.admin')"
            OrdererEndpoints:
                - orderer.test.com:7050
    
        - &Org1
            Name: Org1MSP
            ID: Org1MSP
            MSPDir: crypto-config/peerOrganizations/org1.test.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('Org1MSP.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('Org1MSP.peer')"
            AnchorPeers:
                - Host: peer0.org1.test.com
                  Port: 7051
    
        - &Org2
            Name: Org2MSP
            ID: Org2MSP
            MSPDir: crypto-config/peerOrganizations/org2.test.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('Org2MSP.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('Org2MSP.peer')"
            AnchorPeers:
                - Host: peer0.org2.test.com
                  Port: 7051
    
        - &Org3
            Name: Org3MSP
            ID: Org3MSP
            MSPDir: crypto-config/peerOrganizations/org3.test.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('Org3MSP.admin', 'Org3MSP.peer', 'Org3MSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('Org3MSP.admin', 'Org3MSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('Org3MSP.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('Org3MSP.peer')"
            AnchorPeers:
                - Host: peer0.org3.test.com
                  Port: 7051

    ################################################################################
    #   SECTION: Capabilities
    ################################################################################
    Capabilities:
        Channel: &ChannelCapabilities
            V2_0: true
    
        Orderer: &OrdererCapabilities
            V2_0: true
    
        Application: &ApplicationCapabilities
            V2_0: true        
    
    ################################################################################
    #   SECTION: Application
    ################################################################################
    Application: &ApplicationDefaults
    
        
        
        Organizations:
    
        
        
        
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
            LifecycleEndorsement:
                Type: ImplicitMeta
                Rule: "MAJORITY Endorsement"
            Endorsement:
                Type: ImplicitMeta
                Rule: "MAJORITY Endorsement"
    
        Capabilities:
            <<: *ApplicationCapabilities    
    
    ################################################################################
    #   SECTION: Orderer
    ################################################################################
    Orderer: &OrdererDefaults
        # Orderer Type: The orderer implementation to start
        OrdererType: solo
    
    #    OrdererType: etcdraft
    
        EtcdRaft:
            Consenters:
            - Host: orderer.test.com
              Port: 7050
              ClientTLSCert: ../organizations/ordererOrganizations/test.com/orderers/orderer.test.com/tls/server.crt
              ServerTLSCert: ../organizations/ordererOrganizations/test.com/orderers/orderer.test.com/tls/server.crt
    
        Addresses:
            - orderer.test.com:7050
        BatchTimeout: 2s
        BatchSize:
            MaxMessageCount: 10
            AbsoluteMaxBytes: 99 MB
            PreferredMaxBytes: 512 KB
    
        Kafka:
            Brokers:
                - 127.0.0.1:9092
        Organizations:
    
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
            
            
            BlockValidation:
                Type: ImplicitMeta
                Rule: "ANY Writers"
    
    ################################################################################
    #
    #   CHANNEL
    #
    #   This section defines the values to encode into a config transaction or
    #   genesis block for channel related parameters.
    #
    ################################################################################
    Channel: &ChannelDefaults
        
        
        
        Policies:
            
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
    
        
        
        
        Capabilities:
            <<: *ChannelCapabilities
    
    ################################################################################
    #   Profile
    ################################################################################
    Profiles:
    
        ThreeOrgsOrdererGenesis:
            <<: *ChannelDefaults
            Orderer:
                <<: *OrdererDefaults
                Organizations:
                    - *OrdererOrg
                Capabilities:
                    <<: *OrdererCapabilities
            Consortiums:
                SampleConsortium:
                    Organizations:
                        - *Org1
                        - *Org2
                        - *Org3

        ThreeOrgsChannel:
            Consortium: SampleConsortium
            <<: *ChannelDefaults
            Application:
                <<: *ApplicationDefaults
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3
                Capabilities:
                    <<: *ApplicationCapabilities