version: '2'

services:

  
  orderer.test.com:
    
    container_name: orderer.test.com
    image: hyperledger/fabric-orderer:2.2.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    
    - ../crypto-config/ordererOrganizations/test.com/orderers/orderer.test.com/msp:/var/hyperledger/orderer/msp
    
    - ../crypto-config/ordererOrganizations/test.com/orderers/orderer.test.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  
  peer0.org1.test.com:
    
    container_name: peer0.org1.test.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      
      - CORE_PEER_ID=peer0.org1.test.com
      
      - CORE_PEER_ADDRESS=peer0.org1.test.com:7051
      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.test.com:7051
      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.test.com:7051      
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        
        - ../crypto-config/peerOrganizations/org1.test.com/peers/peer0.org1.test.com/msp:/etc/hyperledger/fabric/msp
       
        - ../crypto-config/peerOrganizations/org1.test.com/peers/peer0.org1.test.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  
  peer0.org2.test.com:
    
    container_name: peer0.org2.test.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      
      - CORE_PEER_ID=peer0.org2.test.com
      
      - CORE_PEER_ADDRESS=peer0.org2.test.com:7051
      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.test.com:7051
      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.test.com:7051
      
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        
        - ../crypto-config/peerOrganizations/org2.test.com/peers/peer0.org2.test.com/msp:/etc/hyperledger/fabric/msp
       
        - ../crypto-config/peerOrganizations/org2.test.com/peers/peer0.org2.test.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:7051
      - 8053:7053

  
  peer0.org3.test.com:
    
    container_name: peer0.org3.test.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
     
      - CORE_PEER_ID=peer0.org3.test.com
      
      - CORE_PEER_ADDRESS=peer0.org3.test.com:7051
     
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.test.com:7051
      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.test.com:7051
      
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        
        - ../crypto-config/peerOrganizations/org3.test.com/peers/peer0.org3.test.com/msp:/etc/hyperledger/fabric/msp
        
        - ../crypto-config/peerOrganizations/org3.test.com/peers/peer0.org3.test.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

